#!/usr/bin/env bash


SCRIPT_CONF="/config/settings.conf"

LOAD_SETTINGS_CONF() {
    RMTASK="$(grep ^remove-task "${SCRIPT_CONF}" | cut -d= -f2-)"
    ANIDIR="$(grep ^ani-dir "${SCRIPT_CONF}" | cut -d= -f2-)"
    MOVDIR="$(grep ^mov-dir "${SCRIPT_CONF}" | cut -d= -f2-)"
    TVDIR="$(grep ^tvs-dir "${SCRIPT_CONF}" | cut -d= -f2-)"
    CUSDIR="$(grep ^cus-dir "${SCRIPT_CONF}" | cut -d= -f2-)"
    MOVE="$(grep ^move "${SCRIPT_CONF}" | cut -d= -f2-)"
    CF="$(grep ^content-filter "${SCRIPT_CONF}" | cut -d= -f2-)"
    DET="$(grep ^delete-empty-dir "${SCRIPT_CONF}" | cut -d= -f2-)"
}
