#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config/ssl \
  /config/backup-torrent \
  /downloads/completed \
  /downloads/recycle

# copy files
if [[ ! -e /config/aria2.conf ]]
then
  cp /aria2/conf/aria2.conf.default /config/aria2.conf
fi

if [[ ! -e /config/setting.conf ]]
then
  cp /aria2/conf/setting.conf /config/setting.conf
fi

# 保留配置、更新修改配置文件
if [[ -e /config/setting.conf ]]
then
  chmod +x /aria2/script/setting
  "/aria2/script/setting"
  cp /aria2/conf/setting.conf /config/setting.conf.new
  sed -i "s@^\(remove-task=\).*@\1${RMTASK}@" /config/setting.conf.new
  sed -i "s@^\(move=\).*@\1${MOVE}@" /config/setting.conf.new
  sed -i "s@^\(content-filter=\).*@\1${CF}@" /config/setting.conf.new
  sed -i "s@^\(delete-empty-dir=\).*@\1${DET}@" /config/setting.conf.new
  sed -i "s@^\(handle-torrent=\).*@\1${TOR}@" /config/setting.conf.new
  sed -i "s@^\(remove-repeat-task=\).*@\1${RRT}@" /config/setting.conf.new
  rm -f /config/setting.conf
  mv /config/setting.conf.new /config/setting.conf
fi

if [[ ! -e /config/文件过滤.conf ]]
then
  cp /aria2/conf/文件过滤.conf /config/文件过滤.conf
fi

if [[ ! -e /config/aria2.session ]]
then
  touch /config/aria2.session
fi

if [[ ! -e /config/dht.dat ]]
then
  touch /config/dht.dat
fi

if [[ ! -e /config/move.log ]]
then
  touch /config/move.log
fi

if [[ ! -e /config/recycle.log ]]
then
  touch /config/recycle.log
fi

if [[ ! -e /config/delete.log ]]
then
  touch /config/delete.log
fi

if [[ ! -e /config/文件过滤日志.log ]]
then
  touch /config/文件过滤日志.log
fi
